spring:
  datasource:
    url: jdbc:mysql://db:3306/sample
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
