spring:
  datasource:
    url: jdbc:mysql://db:3306/sample
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: password
  sql:
    init:
      mode: always
  session:
    store-type: redis
  data:
    redis:
      host: "redis"
logging:
  level:
    org:
      springframework: WARN
    com:
      sireikan:
        gack:
          infrastructure:
            mapper: DEBUG
