spring:
  datasource:
    url: jdbc:mysql://db:3306/sample
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
    ssl: false
    database: 0
    password: password
  devtools:
    remote:
      restart:
        enabled: true
    livereload:
      enabled: true
    restart:
      enabled: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
