spring:
  datasource:
    url: jdbc:mysql://db:3306/sample?autoReconnect=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    store-type: redis
  devtools:
    remote:
      restart:
        enabled: true
    livereload:
      enabled: true
    restart:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379
      ssl: false
      database: 0
      password: password
mybatis:
  configuration:
    map-underscore-to-camel-case: true
