version: '3'

services:
  db:
    image: mysql:8
    container_name: "database"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/sql/:/docker-entrypoint-initdb.d
      - ./mysql/settings/:/var/lib/mysql
      - ./mysql/sql/mysql.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_DATABASE: "sample"
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
      TZ: "Asia/Tokyo"
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ~/src/github.com/sireikan/gack:/app
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - db
